### 1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). 
Применим его к 'tweet_stemmed'
и 'tweet_lemmatized' отдельно.
- Игнорируем слова, частота которых в документе строго превышает порог 0.9 с
помощью max_df.
-  Ограничим количество слов, попадающий в мешок, с помощью max_features=1000.
-  Исключим стоп-слова с помощью stop_words='english'.
-  Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с
помощью CountVectorizer.get_feature_names().

In [28]:
import pandas as pd
import numpy as np
import pickle
import re
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
# загружаем трейн-датасет с прошлого урока
with open('train_tweets.pickle', 'rb') as f:
    train_df = pickle.load(f)

In [30]:
train_df.head(3)

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...",father dysfunct selfish drag kid dysfunct run,father dysfunctional selfish drag kid dysfunct...
1,2,0,thanks for lyft credit can not use cause they ...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...",thank lyft credit use caus offer wheelchair va...,thanks lyft credit use cause offer wheelchair ...
2,3,0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]",bihday majesti,bihday majesty

In [31]:
# загружаем тест-датасет с прошлого урока
with open('test_tweets.pickle', 'rb') as f:
    test_df = pickle.load(f)

In [32]:
test_df.head(3)

,id,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,31963,studiolife aislife requires passion dedication...,"[studiolife, aislife, requires, passion, dedic...","[studiolife, aislife, requires, passion, dedic...",studiolif aislif requir passion dedic willpow ...,studiolife aislife requires passion dedication...
1,31964,white supremacists want everyone to see the ne...,"[white, supremacists, want, everyone, to, see,...","[white, supremacists, want, everyone, see, new...",white supremacist want everyon see new bird movi,white supremacist want everyone see new bird m...
2,31965,safe ways to heal your acne altwaystoheal heal...,"[safe, ways, to, heal, your, acne, altwaystohe...","[safe, ways, heal, acne, altwaystoheal, health...",safe way heal acn altwaystoh healthi heal,safe way heal acne altwaystoheal healthy healing

In [33]:
count_vectorizer = CountVectorizer(ngram_range=(1, 1), max_df=0.9,  max_features=1000, stop_words='english')

In [34]:
train_bow_stemmed = count_vectorizer.fit_transform(train_df['tweet_stemmed'])
feature_names = count_vectorizer.get_feature_names()

pd.DataFrame(train_bow_stemmed.toarray(), columns=feature_names)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,year,yesterday,yo,yoga,york,young,youth,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31958,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31959,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31960,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31961,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [109]:
train_bow_lemmatized = count_vectorizer.fit_transform(train_df['tweet_lemmatized'])
feature_names = count_vectorizer.get_feature_names()

train_lemm_df = pd.DataFrame(train_bow_lemmatized.toarray(), columns=feature_names)
train_lemm_df

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yo,yoga,york,young,youth,youtube,yr,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31958,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31959,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31960,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31961,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [110]:
test_bow_lemmatized = count_vectorizer.transform(test_df['tweet_lemmatized'])
feature_names = count_vectorizer.get_feature_names()

test_lemm_df = pd.DataFrame(train_bow_lemmatized.toarray(), columns=feature_names)
test_lemm_df

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yo,yoga,york,young,youth,youtube,yr,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31958,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31959,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31960,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31961,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 2. Создайте мешок слов 
с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и
'tweet_lemmatized' отдельно.
-  Игнорируем слова, частота которых в документе строго превышает порог 0.9 с
помощью max_df.
- Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
- Исключим стоп-слова с помощью stop_words='english'.
- Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с
помощью TfidfVectorizer.get_feature_names().

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.9, max_features=1000, stop_words='english')

In [38]:
train_tfidf_stemmed = tfidf_vectorizer.fit_transform(train_df['tweet_stemmed'])
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(train_tfidf_stemmed.toarray(), columns = feature_names)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,year,yesterday,yo,yoga,york,young,youth,youtub,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31959,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31960,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31961,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
train_tfidf_lemmatized = tfidf_vectorizer.fit_transform(train_df['tweet_lemmatized'])
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(train_tfidf_lemmatized.toarray(), columns = feature_names)

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yes,yesterday,yo,yoga,york,young,youth,youtube,yr,yummy
0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31958,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31959,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31960,0.0,0.0,0.0,0.662838,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31961,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 3. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, 
составьте таблицу метод векторизации и скор который вы получили (в методах векторизации поизменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [43]:
PATH = '/Users/admin/Desktop/GeekBrains/NLP/2-Создание признакового пространства/corpus.txt'

In [148]:
# Загружаем данные
data = open(PATH).read()

In [149]:
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
df = pd.DataFrame()
df['text'] = texts
df['label'] = labels
df.head(5)

                                                text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    10000 non-null  object
 1   label   10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB

In [69]:
df['label'].value_counts()

__label__1    5097
__label__2    4903
Name: label, dtype: int64

### Предобработка текста

In [151]:
# замена апострофов
apostrophe_dict = {"ain't": "am not", "can't":"can not", "isn't": "is not", "don't": "do not", 
                 "doesn't": "does not", "won't": "will not",
                  "aren't": "are not", "wasn't": "was not", "didn't": "did not", "I'm":"I am",
                  "hasn't": "has not"}

def replace_apostrophe(text):
    return " ".join(apostrophe_dict.get(x, x) for x in text.split())

df['text'] = df['text'].apply(replace_apostrophe)

In [152]:
def remove_punct(string):
    punct_pattern = re.compile('[^\w\s]+')
    return punct_pattern.sub(r' ', string)

df['text'] = df['text'].apply(remove_punct)

In [153]:
def remove_symb(string):
    punct_pattern = re.compile('[^a-zA-Z0-9]')
    return punct_pattern.sub(r' ', string)

df['text'] = df['text'].apply(remove_symb)

In [154]:
def remove_digit(string):
    punct_pattern = re.compile('[^a-zA-Z]')
    return punct_pattern.sub(r' ', string)

df['text'] = df['text'].apply(remove_digit)

In [158]:
def del_short_word(text):
    return " ".join([w for w in text.split() if len(w)>1])

df['text'] = df['text'].apply(del_short_word)

In [159]:
df.head()

                                                text       label
0  Stuning even for the non gamer This sound trac...  __label__2
1  The best soundtrack ever to anything am readin...  __label__2
2  Amazing This soundtrack is my favorite music o...  __label__2
3  Excellent Soundtrack truly like this soundtrac...  __label__2
4  Remember Pull Your Jaw Off The Floor After Hea...  __label__2

### Инициализация векторайзеров

In [47]:
count_vectorizer_1 = CountVectorizer(ngram_range=(1, 1), max_df=0.9,  max_features=1000, stop_words='english')

In [48]:
count_vectorizer_2 = CountVectorizer(ngram_range=(1, 2), max_df=0.9,  max_features=1000, stop_words='english')

In [51]:
count_vectorizer_3 = CountVectorizer(ngram_range=(2, 2), max_df=0.9,  max_features=1000, stop_words='english')

In [53]:
count_vectorizer_4 = CountVectorizer(ngram_range=(2, 3), max_df=0.9,  max_features=1000, stop_words='english')

In [52]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.9, max_features=1000, stop_words='english')

In [76]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import classification_report

In [160]:
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.25, random_state=42)

In [164]:
# labelEncode для целевой переменной переведем в бинарный формат
encoder = preprocessing.LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [162]:
bow_1 = count_vectorizer_1.fit_transform(X_train) #(ngram_range=(1, 1)
# lr_model = LinearRegression(random_state=42)
gb_model = GradientBoostingRegressor(max_depth=5,
                                     min_samples_leaf=7,
                                     random_state=42,  
                                     n_estimators=100)

In [168]:
# списки для сохранения результатов
vect_method = ['Count_vectorizer_ngram_(1,1)', 'Count_vectorizer_ngram_(1,2)', 'Count_vectorizer_ngram_(2,2)',
               'Count_vectorizer_ngram_(2,3)','Tfidf']
score = []

In [169]:
gb_model.fit(bow_1, y_train)

GradientBoostingRegressor(max_depth=5, min_samples_leaf=7, random_state=42)

In [170]:
pred = gb_model.predict(count_vectorizer_1.transform(X_test))
print(classification_report(pred.round(), y_test))

              precision    recall  f1-score   support

         0.0       0.80      0.81      0.81      1270
         1.0       0.80      0.80      0.80      1230

    accuracy                           0.80      2500
   macro avg       0.80      0.80      0.80      2500
weighted avg       0.80      0.80      0.80      2500

In [171]:
from sklearn import metrics
f1_score_1 = metrics.f1_score(pred.round(), y_test)
score.append(f1_score_1)
f1_score_1

0.7999999999999999

In [172]:
bow_2 = count_vectorizer_2.fit_transform(X_train)  #(ngram_range=(1, 2)
gb_model.fit(bow_2, y_train)
pred_2 = gb_model.predict(count_vectorizer_2.transform(X_test))
print(classification_report(pred_2.round(), y_test))

              precision    recall  f1-score   support

         0.0       0.80      0.82      0.81      1261
         1.0       0.81      0.79      0.80      1239

    accuracy                           0.80      2500
   macro avg       0.80      0.80      0.80      2500
weighted avg       0.80      0.80      0.80      2500

In [173]:
f1_score_2 = metrics.f1_score(pred_2.round(), y_test)
score.append(f1_score_2)
f1_score_2

0.8003259983700082

In [174]:
bow_3 = count_vectorizer_3.fit_transform(X_train)  #ngram_range=(2, 2)
gb_model.fit(bow_3, y_train)
pred_3 = gb_model.predict(count_vectorizer_3.transform(X_test))
print(classification_report(pred_3.round(), y_test))

              precision    recall  f1-score   support

         0.0       0.92      0.60      0.73      1954
         1.0       0.36      0.81      0.50       546

    accuracy                           0.65      2500
   macro avg       0.64      0.71      0.61      2500
weighted avg       0.80      0.65      0.68      2500

In [175]:
f1_score_3 = metrics.f1_score(pred_3.round(), y_test)
score.append(f1_score_3)
f1_score_3

0.5008517887563885

In [176]:
bow_4 = count_vectorizer_4.fit_transform(X_train)  #ngram_range=(2, 3)
gb_model.fit(bow_4, y_train)
pred_4 = gb_model.predict(count_vectorizer_4.transform(X_test))
print(classification_report(pred_4.round(), y_test))

              precision    recall  f1-score   support

         0.0       0.92      0.60      0.73      1954
         1.0       0.36      0.81      0.50       546

    accuracy                           0.65      2500
   macro avg       0.64      0.71      0.61      2500
weighted avg       0.80      0.65      0.68      2500

In [177]:
f1_score_4 = metrics.f1_score(pred_4.round(), y_test)
score.append(f1_score_4)
f1_score_4

0.5008517887563885

In [178]:
bow_tfidf = tfidf_vectorizer.fit_transform(X_train)  #tfidf
gb_model.fit(bow_tfidf, y_train)
pred_5 = gb_model.predict(tfidf_vectorizer.transform(X_test))
print(classification_report(pred_5.round(), y_test))

              precision    recall  f1-score   support

         0.0       0.81      0.80      0.80      1291
         1.0       0.79      0.79      0.79      1209

    accuracy                           0.80      2500
   macro avg       0.80      0.80      0.80      2500
weighted avg       0.80      0.80      0.80      2500

In [179]:
f1_score_5 = metrics.f1_score(pred_5.round(), y_test)
score.append(f1_score_5)
f1_score_5

0.7912541254125414

In [180]:
result_df = pd.DataFrame(score, index=vect_method, columns=['F1-score'])
result_df.sort_values(by='F1-score', ascending=False)

                              F1-score
Count_vectorizer_ngram_(1,2)  0.800326
Count_vectorizer_ngram_(1,1)  0.800000
Tfidf                         0.791254
Count_vectorizer_ngram_(2,2)  0.500852
Count_vectorizer_ngram_(2,3)  0.500852

Наилучшие метрики показал Count_vectorizer с параметром ngram_range=(1,2)

### Снижение размерности с помощью PCA

In [181]:
from sklearn.decomposition import PCA

In [182]:
pca = PCA(n_components=10, random_state=42)

In [183]:
feature_names = count_vectorizer_1.get_feature_names()
X_train_lemm = pd.DataFrame(bow_1.toarray(), columns = feature_names)
X_train_lemm

,able,absolutely,accurate,act,acting,action,actor,actors,actual,actually,...,write,writer,writing,written,wrong,wrote,year,years,yes,young
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0

In [184]:
bow_1_test = count_vectorizer_1.transform(X_test)
X_test_lemm = pd.DataFrame(bow_1_test.toarray(), columns = feature_names)
X_test_lemm.head()

,able,absolutely,accurate,act,acting,action,actor,actors,actual,actually,...,write,writer,writing,written,wrong,wrote,year,years,yes,young
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [185]:
X_train_pca = pca.fit_transform(X_train_lemm)
len(X_train_pca)

7500

In [186]:
X_test_pca = pca.transform(X_test_lemm)
X_test_pca

array([[ 3.37574946e-01, -3.35038577e-01, -3.01671750e-01, ...,
        -7.21312893e-03, -4.51672636e-02,  1.39007166e-01],
       [ 1.24652836e+00,  1.24265404e-01,  4.27348520e-01, ...,
        -4.00168092e-01, -7.74098501e-02,  2.20651818e-01],
       [ 2.27391937e+00,  2.93560948e-01,  6.62104161e-02, ...,
        -2.13723741e-03, -1.06116550e-01,  4.47190299e-01],
       ...,
       [ 3.31876398e-01, -1.74224703e-01,  5.03193028e-01, ...,
         4.01772958e-01, -3.46696479e-01, -2.36987425e-01],
       [ 3.98638700e+00,  2.54813636e-01,  1.65242769e-01, ...,
         3.65718768e-01, -1.97696265e-01, -1.43770574e-01],
       [-7.20609245e-01, -2.26372394e-01,  6.26835688e-01, ...,
         7.03283093e-01,  4.96298150e-01,  3.48123714e-01]])

In [187]:
gb_model.fit(X_train_pca, y_train)
pred_pca = gb_model.predict(X_test_pca)
print(classification_report(pred_pca.round(), y_test))

              precision    recall  f1-score   support

         0.0       0.69      0.71      0.70      1250
         1.0       0.70      0.68      0.69      1250

    accuracy                           0.69      2500
   macro avg       0.69      0.69      0.69      2500
weighted avg       0.69      0.69      0.69      2500

In [191]:
f1_score_pca = metrics.f1_score(pred_pca.round(), y_test)
print(round(f1_score_pca, 3))

0.689

Сокращение размерности модели методом PCA до 10 компонент привело к довольно неплохому качеству по метрике F1-score. Зато число фичей в разы уменьшилось с 1000 до 10 (по сравнению с CountVectorizer).

In [194]:
# попробуем снизить размерность до 500 компонент:
pca_50 = PCA(n_components=50, random_state=42)
X_train_pca_50 = pca_50.fit_transform(X_train_lemm)
X_test_pca_50 = pca_50.transform(X_test_lemm)

In [195]:
gb_model.fit(X_train_pca_50, y_train)
pred_pca_50 = gb_model.predict(X_test_pca_50)
print(classification_report(pred_pca_50.round(), y_test))

              precision    recall  f1-score   support

         0.0       0.75      0.76      0.76      1256
         1.0       0.76      0.74      0.75      1244

    accuracy                           0.75      2500
   macro avg       0.75      0.75      0.75      2500
weighted avg       0.75      0.75      0.75      2500

В результате снжения размерности в 20 раз (с 1000 до 50 фичей) получили отличное качество у модели, сравнимое с tdidf-векторайзером на 1000 признаков.